### ISSUE TITLE
Missing Attribute get

### ISSUE THREAD

**Issue by MichiFr** [openviess/PyViCare#120]
Hi!

First of all thanks for this great lib and the maintenance of the repository! I'm using it for long time now and pushing metrics from Viessmann servers to a local InfluxDB with attached Grafana dashboard.

Today I've updated PyViCare to get the api request running with Viessmann new requirements. I've created a test script using the Basic Usage example here from README.md.

When executing the script I immediately get this error:
```
  File "C:\Users\Michael\AppData\Local\Programs\Python\Python38\lib\site-packages\PyViCare\PyViCareService.py", line 201, in __get
    r=self.oauth.get(url).json()
AttributeError: 'NoneType' object has no attribute 'get'
```
Did I miss the obvious? I've created a client ID and inserted username and password as well as the new client ID to the basic script above. So basically it should work.

Any hint why the authentication fails?

Michael

**Comment by woehrl01** [comment]
Hi @MichiFr as you already found out, the `AttributeError` happens due to a failed authentication.
1. Which library version do you use? 
2. Do you have correctly configured the OAuth callback URL on the Viessmann Dev Portal? `vicare://oauth-callback/everest` and disabled reCAPTCHA?

If you think everything looks right. Please verify the correct credentials by using Postman as described in the readme.

**Comment by woehrl01** [comment]
I close the issue for now, if you still encounter the issue, I'm happy to reopen.
