### ISSUE TITLE
getCurrentDesiredTemperature for standby is throwing not supported error

### ISSUE THREAD

**Issue by woehrl01** [openviess/PyViCare#197]
The only "circuit"-function not working since the last api-update is getCurrentDesiredTemperature().
error-message: 

```
site-packages\PyViCare\PyViCareUtils.py", line 45, in feature_flag_wrapper return wrapper(*args, **kwargs)
site-packages\PyViCare\PyViCareUtils.py", line 40, in wrapper raise PyViCareNotSupportedFeatureError(func.__name__)
PyViCare.PyViCareUtils.PyViCareNotSupportedFeatureError: getCurrentDesiredTemperature
```

_Originally posted by @kruemel746 in https://github.com/somm15/PyViCare/issues/194#issuecomment-931603388_

**Comment by woehrl01** [comment]
@kruemel746 According to your debug output it looks like that your current active program is `Standby` which has no desired temperature to my knowledge. At least, the new API does not return a value for that program type. 

Do you remember the old behaviour? 

The question is if we should throw "NotSupported" or simply return `None` in that case? (Thoughts @oischinger , @crazyfx1 ?)

**Comment by kruemel746** [comment]
Sorry, my fault! I'm not sure, but I think before also an error was triggered, which I caught myself and simply replaced the value with "getDesiredTemperatureForProgram("normal")" - which was acceptable for my usecase.
I have now tested the code outside my main program and did not think of it.

**Comment by woehrl01** [comment]
I just tested the output, it looks like that the behaviour did not change, despite that it's still something to think about. Personally, would prefer returning `None` in that case. Thanks for the hint, I'll keep the issue open for now.

**Comment by oischinger** [comment]
The HA integration now uses the notsupported exceptions to identify if a sensor is generally supported or not.
If we want to keep that logic I would prefer to use None for temporarily not supported data

**Comment by woehrl01** [comment]
Thanks @oischinger for you opinion. I agree with you, so I'm returning `None`. I need to have a look for other values where this behavior should be changed similar.

**Comment by stef-g** [comment]
I am using a Vitodens 300-W (E3) and use automations in Home Assistant to set the temperature for the "reduced" program based on a schedule (or for program "normal" would make no difference, whatever program you would define on the Vitodens schedule). Problem is that if outside temperature has certain values, the Vitodens switches to program "standby" (even though it should stay in "reduced" but the device doesn't). If this happens, the automations fail since for program standby the temperature cannot be set (I am not a coder but believe this happens here:"return self.service.setProperty(f"heating.circuits.{self.circuit}.operating.programs.{program}", "setTemperature", ...").

Seems to me there should be additional code if the current program is standby to choose i.e. reduced (or in my case I would prefer to always only set temperature for program reduced as I want to automate via Home Assistant and do not care about the ViCare schedule with the different programs for reduced, normal and comfort.

There is a similar issue in the Home Assistant ViCare integration listed but no answers. Believe PyViCare would be the place to fix this. I am not familiar with GitHub and as said I am not a coder. How would I get help, believe this would affect many others as well. 

Thank you so much for pointing me in the right direction!

**Comment by tobyps** [comment]
@stefangersbach You should be able to set the temperature at which it enters standby in the menu of the device. (Check the installationmanual not the user manual).
As far as I know its not possible to set those values via the API

**Comment by stef-g** [comment]
I don't think that it has to do with the configuration setting of the Vitodens. In the config of the Vitodens (using vimaster mode) it is set to turn off the heater at 17 degrees outside temperature. Now it has 13 degrees outside temperature though and it still changes to standby.

**Comment by stef-g** [comment]
Was able to come up with 2 possible workarounds for my Vitodens 300W (E3):

First I automated in a cumbersome way to never set the target temperature too low (never to 3 degrees), and instead set the mode to standby at night, then in the morning to dhwandheating again where I already had a relatively high value of either 18, 20 or 21 degrees for the "reduced" program depending on certain conditions. That way I would never run into the problem as described above.

A few days later I came across a better solution as shared by @hnykda here: https://github.com/somm15/PyViCare/issues/240#issuecomment-1365905653

With this pyscript you can use a Home Assistant service to set the temperatures for the programs reduced, normal and comfort independently of which current program is in use. And it works fine independently from the current mode of the heater, even when it is in standby mode (as with my Vitodens it goes into standby automatically depending on the outside temperature even though another program is set by the Vitodens device schedule!).

Anyways, a direct implementation in PyViCare or in the Home Assistant ViCare integration by @oischinger would be great at some point in time. Thank you!
