### ISSUE TITLE
Wrong URL in Postman Instructions

### ISSUE THREAD

**Issue by MichiFr** [openviess/PyViCare#203]
Hi,

Step 2 in the API Postman instructions, tells me to use the URL [https://api.viessmann.com/iot/v1/equipment/installations?includeGateways=true](url)

This one is obviously wrong as it still uses the v1 API.  The same applies to the URL in step 3 as this uses the v1 API, too.

Is there anything else I could use to get the gateway serial and installation ID?

Thanks,
Michael

**Comment by MichiFr** [comment]
Hm, just used those URLs again and out of a sudden they now work despite the fact of a presumbly v1 API call?
Maybe its due to a previous login to the Viessmann developer portal?

**Comment by woehrl01** [comment]
Hi @MichiFr, V1 is the correct version, according to the docs of viessmann for this type of data. Why do you think it's the wrong url?

**Comment by MichiFr** [comment]
Because of the v1 term in the URL. I got the impression that Viessmann recently changed to version 2 of its API, but I was wrong. The authentification works perfectly well in Postman and PyViCare.

OTH, with the latest release of PyViCare, I've to change all of my coding to get it working again. But that's a different story and is my personal fate.

BTW, before the main restructure of the PyViCare library, I've added some more properties in my own wrapper library to get additional details and information from my gaz boiler. Some of those properties are still available in the Viessmann API, some are not because of their recent changes.

What is the correct way of posting still working properties to get them merged into the Github coding? Doing a pull request, adding those properties and committing those changes? I'm yet not very firm in git if it comes to those collaborative projects, you know.

**Comment by crazyfx1** [comment]
Yes, creating a fork, implement the changes (and unit tests) and then create a PR is the way to go ;)

**Comment by woehrl01** [comment]
You're correct @MichiFr there was an API version change. The change was only affecting the login, as the client ID has been added and the overall way to authenticate has changed a bit. The V1 for the properties is still the same, except that due to accessing the API with a "free" API key, a few features are not supported and thus are not available any more. The overall API is still valid, though.

If you have additional properties in your response which are not implemented, it would be great as @crazyfx1 suggest creating a PR which includes your example response and added unit tests. This should be straight forwards. As currently is also Hacktoberfest this is a great opportunity for a free T-Shirt 😄 . (see https://hacktoberfest.digitalocean.com/)

**Comment by woehrl01** [comment]
I'm closing the issue for now, if you want to add additional properties feel free to provide a PR or open a new issue.
