### ISSUE TITLE
 'pip install pyvicare' doesn't work anymore on Raspberry PI

### ISSUE THREAD

**Issue by Mugridge** [openviess/PyViCare#311]
In the past I installed PyViCare a few times without problems using the command  'pip install pyvicare' or 'pip3 install pyvicare'. Since yesterday it doesn't work. The installation starts with the following messages and creates the first error message:

> 
 Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyvicare
  Using cached https://www.piwheels.org/simple/pyvicare/PyViCare-2.27.2-py3-none-any.whl (30 kB)
Collecting Authlib>=1.2.0
  Using cached https://www.piwheels.org/simple/authlib/Authlib-1.2.0-py2.py3-none-any.whl (214 kB)
Collecting cryptography>=3.2
  Using cached cryptography-40.0.2.tar.gz (625 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting cffi>=1.12
  Using cached https://www.piwheels.org/simple/cffi/cffi-1.15.1-cp39-cp39-linux_armv7l.whl (364 kB)
Collecting pycparser
  Using cached https://www.piwheels.org/simple/pycparser/pycparser-2.21-py2.py3-none-any.whl (119 kB)
Building wheels for collected packages: cryptography
  Building wheel for cryptography (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmpx6nj4x3h_in_process.py build_wheel /tmp/tmpancn0ema
       cwd: /tmp/pip-install-b0mmhol3/cryptography_2fef41ca35804d6797c868ec53c2e5f1
  Complete output (247 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
>
 
After that the installation continous and creates the next errormessage:
>
/tmp/pip-build-env-tqmmz5oi/overlay/lib/python3.9/site-packages/setuptools/command/build_py.py:201: _Warning: Package 'cryptography.hazmat.bindings._rust' is absent from the `packages` configuration.
  !!

          ********************************************************************************
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'cryptography.hazmat.bindings._rust' as an importable package[^1],
          but it is absent from setuptools' `packages` configuration.

>
and finally
error: can't find Rust compiler

  If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

  To update pip, run:

      pip install --upgrade pip

  and then retry package installation.

  If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.

  This package requires Rust >=1.48.0.
  ----------------------------------------
  ERROR: Failed building wheel for cryptography
Failed to build cryptography
ERROR: Could not build wheels for cryptography which use PEP 517 and cannot be installed directly
`
The same command works a few days ago with the same raspberry image 2023-02-21-raspios-bullseye-armhf-lite and the newest updates. Fortunately I have a backup with a working installation.
I have no idea how to fix this problem.

**Comment by SPITZGITHUB** [comment]
I get no data from pyvicare since today 11.05.2023 05:30 and when I like to update the Pyvicare I have the same problems as shown above. 

Then I started Python directly and try to run the programm but then I got the following errors:
  File "C:\Users\Peter\.spyder-py3\temp.py", line 11, in <module>
    vicare.initWithCredentials(email, password, client_id, "token.save")
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyViCare\PyViCare.py", line 24, in initWithCredentials
    self.initWithExternalOAuth(ViCareOAuthManager(
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyViCare\PyViCare.py", line 29, in initWithExternalOAuth
    self.__loadInstallations()
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyViCare\PyViCare.py", line 43, in __loadInstallations
    self.devices = list(self.__readInstallations(installations["data"]))
KeyError: 'data'

What is wrong? I have no idea how to fix this problem. Please help

**Comment by woehrl01** [comment]
@crazyfx1 do you have any idea what this could have caused? Has this something to do with the change of the oauth flow?

**Comment by crazyfx1** [comment]
The API had massive outages yesterday and seems like it's not fixed for everybody yet:
https://community.home-assistant.io/t/viessmann-component/77873/879

**Comment by crazyfx1** [comment]
The install error could indeed come from the new authlib. The Authlib uses cryptography which seems to have this issue.
https://github.com/pyca/cryptography/issues/5753

They suggest upgrading pip which you already did. Furthermore they suggest trying to add the --prefer-binary switch.

**Comment by Mugridge** [comment]
I installed a clean image on the raspberry, did the minimal settings for network and localisation, made an update and installed pip3 because pip is no more supported:

 sudo apt-get install python3-pip

I got the pip 20.3.4 version. After that I updated pip3 whith the --prefer-binary option:

$ pip3 install --upgrade pip --prefer-binary

And I got the 23.1.2 Version with the following message:
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: pip in /usr/lib/python3/dist-packages (20.3.4)
Collecting pip
  Downloading https://www.piwheels.org/simple/pip/pip-23.1.2-py3-none-any.whl (2.1 MB)
     |¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦| 2.1 MB 1.2 MB/s
Installing collected packages: pip
  WARNING: The scripts pip, pip3 and pip3.9 are installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed pip-23.1.2

After that I tried to install PyViCare:

pip3 install pyvicare

And got a different error message at the same position:

Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyvicare
  Downloading https://www.piwheels.org/simple/pyvicare/PyViCare-2.27.2-py3-none-any.whl (30 kB)
Collecting Authlib>=1.2.0 (from pyvicare)
  Downloading https://www.piwheels.org/simple/authlib/Authlib-1.2.0-py2.py3-none-any.whl (214 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.8/214.8 kB 2.1 MB/s eta 0:00:00
Collecting cryptography>=3.2 (from Authlib>=1.2.0->pyvicare)
  Downloading cryptography-40.0.2.tar.gz (625 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 625.6/625.6 kB 4.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cffi>=1.12 (from cryptography>=3.2->Authlib>=1.2.0->pyvicare)
  Using cached https://www.piwheels.org/simple/cffi/cffi-1.15.1-cp39-cp39-linux_armv7l.whl (364 kB)
Collecting pycparser (from cffi>=1.12->cryptography>=3.2->Authlib>=1.2.0->pyvicare)
  Using cached https://www.piwheels.org/simple/pycparser/pycparser-2.21-py2.py3-none-any.whl (119 kB)
Building wheels for collected packages: cryptography
  Building wheel for cryptography (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cryptography (pyproject.toml) did not run successfully.
  │ exit code: 1

The rest of the messages seems to be the same like yesterday. I googled some messages and found different results, so the problem is not unique. But I didn't find a common solution. Any suggestions?

**Comment by crazyfx1** [comment]
The hint was to use `--prefer-binary` in the pip install for PyViCare:
`pip3 install PyViCare --prefer-binary`

**Comment by Mugridge** [comment]
Fixed! Issue can be closed. Thank you.

**Comment by SPITZGITHUB** [comment]
I have updated the system with:
**sudo apt update && sudo apt upgrade**
After that I have run the hint above and received:
**pi@raspberrypi:~ $ pip3 install PyViCare --prefer-binary**
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: PyViCare in ./.local/lib/python3.7/site-packages (2.12.0)
Requirement already satisfied: pkce in ./.local/lib/python3.7/site-packages (from PyViCare) (1.0.3)
Requirement already satisfied: requests-oauthlib>=1.1.0 in ./.local/lib/python3.7/site-packages (from PyViCare) (1.3.0)
Requirement already satisfied: oauthlib>=3.0.0 in ./.local/lib/python3.7/site-packages (from requests-oauthlib>=1.1.0->PyViCare) (3.1.1)

Now I started Python and run the code:
# This Python file uses the following encoding: utf-8
**import sys
import logging
from PyViCare.PyViCare import PyViCare

client_id = "XXXXXXXXXXXXXXX"
email = "yyyyyyyyyyyyyy"
password = "XXXXXXXXXXXXXX"

vicare = PyViCare()
vicare.initWithCredentials(email, password, client_id, "token.save")
device = vicare.devices[0]**

and got the answer:

runfile('C:/Users/Peter/.spyder-py3/temp.py', wdir='C:/Users/Peter/.spyder-py3')
Traceback (most recent call last):
File "C:\Users\Peter\.spyder-py3\temp.py", line 11, in <module>
    vicare.initWithCredentials(email, password, client_id, "token.save")

  File "C:\Users\Peter\.conda\envs\spyder\lib\site-packages\PyViCare\PyViCare.py", line 25, in initWithCredentials
    self.initWithExternalOAuth(ViCareOAuthManager(

  File "C:\Users\Peter\.conda\envs\spyder\lib\site-packages\PyViCare\PyViCare.py", line 30, in initWithExternalOAuth
    self.__loadInstallations()

  File "C:\Users\Peter\.conda\envs\spyder\lib\site-packages\PyViCare\PyViCare.py", line 46, in __loadInstallations
    raise PyViCareInvalidDataError(installations)

PyViCareInvalidDataError: {'viErrorId': 'req-2b2a248382954217a93bcfa5dd17c40a', 'statusCode': 401, 'errorType': 'UNAUTHORIZED', 'message': 'Request contain invalid token', 'error': 'NO TOKEN AVAILABLE'}

As  you can see the the last two lines are new after the update of the system (see above some comments before!)

What is wrong?

**Comment by SPITZGITHUB** [comment]
Hello all,

 

I saw that the issue #311 was closed. But I have the issue already.

 

Here what I have done:

 

I have updated the system with:

sudo apt update && sudo apt upgrade

 

After that I have run the hint above and received:

***@***.***:~ $ pip3 install PyViCare --prefer-binary

 

Response: 

Defaulting to user installation because normal site-packages is not writeable

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple

Requirement already satisfied: PyViCare in ./.local/lib/python3.7/site-packages (2.12.0)

Requirement already satisfied: pkce in ./.local/lib/python3.7/site-packages (from PyViCare) (1.0.3)

Requirement already satisfied: requests-oauthlib>=1.1.0 in ./.local/lib/python3.7/site-packages (from PyViCare) (1.3.0)

Requirement already satisfied: oauthlib>=3.0.0 in ./.local/lib/python3.7/site-packages (from requests-oauthlib>=1.1.0->PyViCare) (3.1.1)

 

Now I started Python and run the code with the right ID, Email, password as I  have done the last years…:

 

import sys

import logging

from PyViCare.PyViCare import PyViCare

client_id = "XXXXXXXXXXXXXXX"

email = "yyyyyyyyyyyyyy"

password = "XXXXXXXXXXXXXX"

 

vicare = PyViCare()

vicare.initWithCredentials(email, password, client_id, "token.save")

device = vicare.devices[0]

 

and got the answer:

 

runfile('C:/Users/Peter/.spyder-py3/temp.py', wdir='C:/Users/Peter/.spyder-py3')

Traceback (most recent call last):

File "C:\Users\Peter.spyder-py3\temp.py", line 11, in

vicare.initWithCredentials(email, password, client_id, "token.save")

 

File "C:\Users\Peter.conda\envs\spyder\lib\site-packages\PyViCare\PyViCare.py", line 25, in initWithCredentials

self.initWithExternalOAuth(ViCareOAuthManager(

 

File "C:\Users\Peter.conda\envs\spyder\lib\site-packages\PyViCare\PyViCare.py", line 30, in initWithExternalOAuth

self.__loadInstallations()

 

File "C:\Users\Peter.conda\envs\spyder\lib\site-packages\PyViCare\PyViCare.py", line 46, in __loadInstallations

raise PyViCareInvalidDataError(installations)

 

PyViCareInvalidDataError: {'viErrorId': 'req-2b2a248382954217a93bcfa5dd17c40a', 'statusCode': 401, 'errorType': 'UNAUTHORIZED', 'message': 'Request contain invalid token', 'error': 'NO TOKEN AVAILABLE'}

 

As you can see the the last two lines are new after the update of the system (see above some comments before!)

 

What is wrong? Thanks a lot for your help

 

 

 

 

Von: Lukas Wöhrl ***@***.***> 
Gesendet: Freitag, 12. Mai 2023 14:25 Uhr
An: somm15/PyViCare ***@***.***>
Cc: SPITZGITHUB ***@***.***>; Comment ***@***.***>
Betreff: Re: [somm15/PyViCare] 'pip install pyvicare' doesn't work anymore on Raspberry PI (Issue #311)

 

Closed #311 <https://github.com/somm15/PyViCare/issues/311>  as completed.

**Comment by crazyfx1** [comment]
Can you try deleting the token.save file in your directory and try again? 
If not please reopen another issue, this issue is about an error message on install which you don't have.

**Comment by SPITZGITHUB** [comment]
Thanks for repyl. But where can I find the token.save?

 

Von: Martin ***@***.***> 
Gesendet: Freitag, 12. Mai 2023 15:39 Uhr
An: somm15/PyViCare ***@***.***>
Cc: SPITZGITHUB ***@***.***>; Comment ***@***.***>
Betreff: Re: [somm15/PyViCare] 'pip install pyvicare' doesn't work anymore on Raspberry PI (Issue #311)

 

Can you try deleting the token.save file in your directory and try again?
If not please reopen another issue, this issue is about an error message on install which you don't have.

**Comment by SPITZGITHUB** [comment]
Hello Martin,

I have found the files token.save and deleted it. Now it runs!!!!

 

Thanks a lot!

 

How can I give you a cup of coffee???

 

 

Von: Martin ***@***.***> 
Gesendet: Freitag, 12. Mai 2023 15:39 Uhr
An: somm15/PyViCare ***@***.***>
Cc: SPITZGITHUB ***@***.***>; Comment ***@***.***>
Betreff: Re: [somm15/PyViCare] 'pip install pyvicare' doesn't work anymore on Raspberry PI (Issue #311)

 

Can you try deleting the token.save file in your directory and try again?
If not please reopen another issue, this issue is about an error message on install which you don't have.

**Comment by crazyfx1** [comment]
You can one-time sponsor me here on github although it's not necessary ;)
