### ISSUE TITLE
Vicare Smart Climate - radiator thermostats and sensors

### ISSUE THREAD

**Issue by adorobis** [openviess/PyViCare#47]
As you probably know Viessmann has now on offer smart radiator thermostats and room climate (temp and humidity) sensors. They can be controlled by the Vicare app via the OPTO2 controller. Do you have any plans to implement support for those thermostats and sensors in the PyViCare component? There is not much of documentation for those new devices yet although they are on sale already.

**Comment by idstein** [comment]
Those sensors are all based on zigbee and can be controlled via e.g.  ZHA or zigpy.
The integration via ViCare Cloud API requires additional HTTP requests that are accounted to the total service call limit per day.

**Comment by somm15** [comment]
I personnaly have not plan to work on this. I have only one boiler at home. I actually started this library because I was very frustrated by how closed Viessmann is. Not 0-10V command, no opentherm, no API ... 
So for thermostat and room climate, I use 1-wire thermometer and 0-10v valve actuators.
I would say indeed that home assistant and zigbee is probably the best solution.

**Comment by adorobis** [comment]
Many thanks for your update!
