### ISSUE TITLE
Access data of solar module SM1

### ISSUE THREAD

**Issue by sweh** [openviess/PyViCare#72]
Hi,

I have a solar module "SM1" attached to my Viessmann Gaz boiler. Is it possible to query the status of that module with this library?

I'd like to know, if it's active (heating the water with the solar panels) and what the temperature of the solar panels on the roof is like.

Chers,
  Sebastian

**Comment by Ocrimops** [comment]
Waiting for this as well :)

During summer I heat my pool with the Viessmann installation. I would love to have my pool pump turn on more often when the solar collector harvests the "free heat". That would save lots of money for me!

**Comment by BrechtMo** [comment]
I was also looking for this, especially because this library is used by the vicare integration in Home Assistant.

You could add it easily by adding to the GazBoiler class.

```
    @handleNotSupported
    def getSolarCollectorTemperature(self):
        return self.service.getProperty("heating.solar.sensors.temperature.collector")["properties"]["value"]["value"]

    @handleNotSupported
    def getSolarDHWTemperature(self):
        return self.service.getProperty("heating.solar.sensors.temperature.dhw")["properties"]["value"]["value"]

    @handleNotSupported
    def getSolarPowerProductionToday(self):
        return self.service.getProperty("heating.solar.power.production")["properties"]["day"]["value"][0]
```

Another feature I'd like to suggest is the supply pressure (pressure in the heating circuit). This would allow you to set up an alert when the pressure gets too low.
`service.getProperty("heating.sensors.pressure.supply")["properties"]["value"]["value"]`

I think it's trivial to add but I need to figure out how to... :-)

**Comment by BrechtMo** [comment]
It seems like an additional solar feature has been added recently: status of solar circuit pump (on/off)
`heating.solar.pumps.circuit`

**Comment by woehrl01** [comment]
Thanks, @BrechtMo and @sweh . That should be definitely possible. So that we can add it properly, we need your help, as we don't own a SM1 ourselves.

Please add an example response of the SM1 as a PR (remove the Serial and Installation Id from the JSON).

To generate a device response, you can use [Postman](https://www.postman.com/). You can find a description in the readme.

**Comment by sweh** [comment]
Hi @woehrl01,

the PR #98 already contains the response from my SM1 in the tests. In my opinion this ticket can be closed.

**Comment by woehrl01** [comment]
🙈  Thanks, looks like I missed that PR 😄
