### ISSUE TITLE
Devices features

### ISSUE THREAD

**Issue by prior-philip** [openviess/PyViCare#97]
Team,
this is not an Issue. Its more kind of request for clarification: Maybe worth to add it to Project Wiki.

A) Are all available features of each DeviceType (eg HeatPump) already configured in PyViCareHeatPump.py and PyViCareDevice.py?

B) What is the proposed and most suitable way to add features manually if (A) is answered to no? Do you want users to manipulate one of above scripts?

**Comment by crazyfx1** [comment]
Basically the current implementation of the devices is reverse engineered by looking at the API response and figuring out what properties are useful. Unfortunately this will stop working in 2 days, when the V1 API will stop working.

For the V2 API, you can see all available properties in the Viessmann Developer Portal. If you compare the list you will see, that around half the properties are not available anymore.

So regarding your questions:

A) No. Currently there are way more properties which will stop working. So we have to delete those properties and get a stable version for the V2 API.

B) Since the maintainers only have certain types of heating systems, we need users to provide data for other types. We hope users will try out the V2 API with their heating systems and provide a pull requests including unit tests with their V2 response.

**Comment by prior-philip** [comment]
Sure Im happy to help out with VitoCal200S HeatPump. How can I contribute?
- nevertheless Im not used to work with Github and you do not want me to add code. Surely not! ;)

**Comment by julred** [comment]
I can also perform some test. I own a Viessmann Vitodens 200 + Vitocell 100 with solar panels.
Please let me know if the software is ready to test

**Comment by jborup** [comment]
@julred I added a section to the readme file on how to extract your config: https://github.com/somm15/PyViCare#more-different-devices-for-test-cases-needed

However your setup may not extract all of the info if the devices are connected to the same controller, and hence gives both a device[0] and device[1]. So could be interesting to know your setup better and the output as well.
I do not know the logic from Viessmann and I have not seen a page/list that shows what features are exposed by the new API, but for sure some features like burner statistics does not show up on all devices outside temperatures seems to be another area. I am trying to collect some info and would like to rais ethat question to them based on facts, so if you can provide your output it would be great (preferably via a pull request...)

**Comment by woehrl01** [comment]
I added all known properties with the latest PR see #178.

If you are new properties feel free to add a response dump.
